### PR TITLE
review prototype 

### PR DESCRIPTION
**Pull request by ruffsl**
A placeholder PR to review the current extension prototype of colcon-cache.

You can basically use the lock subverb to cache the current state of the packages in the workspace into lockfiles; either with dirhash, git, etc, depending upon what revision control system is detected using package augmentation extensions. Then when using build or test verbs, event handlers will update cache lock files for successful packages. The lock files also track dependency changes by default, making it simple to ensure upstream changes break downstream package caches. The package selection extensions enable users to filter packages by how the package source has changed, or if the current verb's cache for selected packages remain valid. See the Readme for example usage.

Preliminary feedback on extension architecture or suggestions for unit/system testing are welcome.

### CODE REVIEW

**Comment by ruffsl** [comment]
FYI I'll be doing a show an tell about this during tomorrow's Tooling Working Group meeting.
Context: https://github.com/colcon/colcon-package-selection/issues/25

CC'ing colcon contributors and perhaps interested parties in case you'd like to drop by:
@dirk-thomas @rotu @tfoote @cottsay @jacobperron @sloretz @mikaelarguedas @mikepurvis @emersonknapp @tylerjw

**Comment by ruffsl** [comment]
BTW, @SteveMacenski @nuclearsandwich, this is the extension I was envisioning to be able to cache entire colcon workspaces across CI runs, so CI Jobs could intelligently build and test only the packages that have changed from the target PR and/or previous run/commit.

**Comment by mikepurvis** [comment]
@ruffsl I'm interested. Please invite me to the meeting.

**Comment by ruffsl** [comment]
> @ruffsl I'm interested. Please invite me to the meeting.

@mikepurvis , Calendar invites for ROS working groups should be publicly accessable from the ROS events calendar:

https://docs.ros.org/en/rolling/Governance.html#upcoming-ros-events

The agenda for the Tooling WG is also viewable here:

https://docs.google.com/document/d/1UXWaEkT6ji0Z0uTtJJSni5Y6fiopM9qOOzv4ldeNaAM/edit?usp=drivesdk

**Comment by nuclearsandwich** [comment]
Thanks for the ping. I'll do my best to join the show&tell tomorrow.

**Comment by ruffsl** [comment]
Here is an example of colcon-cache in action for caching builds and tests in CI: https://github.com/ruffsl/navigation2/pull/6

**Pull request merged**
