### PR TITLE
Use colcon/ci for GitHub Actions

### PR DESCRIPTION
**Pull request by ruffsl**
https://github.com/ruffsl/colcon-clean/pull/21

### CODE REVIEW

**Comment by ruffsl** [comment]
@cottsay , I'm not sure why `scandir` isn't being installed on windows as well when installing the declared `scantree` dependency:

```
       File "C:\hostedtoolcache\windows\Python\3.10.6\x64\lib\site-packages\scantree\compat.py", line 22, in <module>
      from scandir import scandir as _scandir
  ModuleNotFoundError: No module named 'scandir'
```

https://github.com/ruffsl/colcon-cache/runs/8270663254?check_suite_focus=true#step:4:405

**Comment by cottsay** [comment]
I believe this is an upstream bug, likely related to andhus/scantree#4 and the corresponding fix. In Python 3.7, `scandir` shouldn't be needed, but the attempted import from `posix` is failing on Windows and triggering the `except ImportError` even though that was intended to handle a failed import of `os.scandir`. At least that's my theory.

We could probably work around it by declaring a dependency from this package on `scandir` that only applies to win32.

**Comment by ruffsl** [comment]
@cottsay , Have you seen this before on windows?

>   E               pytest.PytestUnraisableExceptionWarning: Exception ignored in: <socket.socket fd=-1, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=0>

https://github.com/ruffsl/colcon-cache/runs/8285905936?check_suite_focus=true#step:4:342

We could filter it, but not sure it should be? Looks like its a commonly filtered by others:

https://grep.app/search?q=PytestUnraisableExceptionWarning&filter[lang][0]=INI

**Comment by ruffsl** [comment]
Don't suppose pytest has a way to block control flow on joins of all underlying async function calls?

>   E                   PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\RUNNER~1\\AppData\\Local\\Temp\\test_colcon_yvagkwr3\\log\\build_2022-09-10_16-53-45\\logger_all.log'

https://github.com/ruffsl/colcon-cache/runs/8286092696?check_suite_focus=true#step:4:355

Guess we can workaround with 6ddaa020a6f73c0ff0c5eabdb939c9d6fc583ead anyhow.

**Comment by ruffsl** [comment]
Ok, I don't know why the coverage report is under reporting. The tests are running, but the coverage.xml doesn't seem to reflect the covered control flow from executed tests. Any ideas?

**Comment by ruffsl** [comment]
I think it might still be using the default branch's codecov.yml file, so I'm going to merge to check.

**Comment by ruffsl** [comment]
@cottsay , I still haven't figured out how to restore the code coverage reports. Is there a setting for colcon CI that is missing? The coverage.xml seems to cover line imports of the code, but does not follow the line execution from the running tests.

**Pull request merged**
